# Generated by Django 3.0.5 on 2020-04-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.CharField(blank=True, max_length=5000, null=True)),
                ('post_title', models.CharField(blank=True, max_length=100, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='date field')),
            ],
        ),
    ]
