# Generated by Django 3.0.5 on 2020-04-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('streams', '0001_initial'),
        ('posts', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='followed_by',
            field=models.ManyToManyField(blank=True, to='users.User'),
        ),
        migrations.AddField(
            model_name='stream',
            name='posts',
            field=models.ManyToManyField(blank=True, to='posts.Post'),
        ),
    ]
